apiVersion: v1
kind: Secret
metadata:
  name: {{ include "probot.fullname" . }}
type: Opaque
data:
  WEBHOOK_SECRET: {{ required "probot.webhookSecret is required" .Values.probot.webhookSecret | b64enc | quote }}
  PRIVATE_KEY: {{ required "probot.privateKey is required" .Values.probot.privateKey | b64enc | quote }}
