apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "probot.fullname" . }}
  labels:
{{ include "probot.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "probot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "probot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /bin/sh
        args:
        - '-c'
        - '. /etc/probot/run.sh'
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
        - name: PORT
          value: "80"
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: {{ include "probot.fullname" . }}
              key: LOG_LEVEL
        - name: APP_ID
          valueFrom:
            configMapKeyRef:
              name: {{ include "probot.fullname" . }}
              key: APP_ID
        - name: WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "probot.fullname" . }}
              key: WEBHOOK_SECRET
        - name: PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "probot.fullname" . }}
              key: PRIVATE_KEY
        volumeMounts:
        - name: configmap
          mountPath: /etc/probot/
      volumes:
      - name: configmap
        configMap:
          name: {{ include "probot.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
